# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import prismGrpc_pb2 as prismGrpc__pb2


class PrismProtoServiceStub(object):
    """Service Definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitPrismLog = channel.unary_unary(
                '/PrismProtoService/InitPrismLog',
                request_serializer=prismGrpc__pb2.InitPrismLogRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.InitResponse.FromString,
                )
        self.InitModulesFile = channel.unary_unary(
                '/PrismProtoService/InitModulesFile',
                request_serializer=prismGrpc__pb2.InitModulesFileRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.InitResponse.FromString,
                )
        self.InitPrism = channel.unary_unary(
                '/PrismProtoService/InitPrism',
                request_serializer=prismGrpc__pb2.InitPrismRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.InitResponse.FromString,
                )
        self.InitPropertiesFile = channel.unary_unary(
                '/PrismProtoService/InitPropertiesFile',
                request_serializer=prismGrpc__pb2.InitPropertiesFileRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.InitResponse.FromString,
                )
        self.InitPropertyObject = channel.unary_unary(
                '/PrismProtoService/InitPropertyObject',
                request_serializer=prismGrpc__pb2.InitPropertyObjectRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.InitResponse.FromString,
                )
        self.InitResult = channel.unary_unary(
                '/PrismProtoService/InitResult',
                request_serializer=prismGrpc__pb2.InitResultRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.InitResponse.FromString,
                )
        self.InitUndefinedConstants = channel.unary_unary(
                '/PrismProtoService/InitUndefinedConstants',
                request_serializer=prismGrpc__pb2.InitUndefinedConstantsRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.InitResponse.FromString,
                )
        self.InitValues = channel.unary_unary(
                '/PrismProtoService/InitValues',
                request_serializer=prismGrpc__pb2.InitValuesRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.InitResponse.FromString,
                )
        self.DeleteObject = channel.unary_unary(
                '/PrismProtoService/DeleteObject',
                request_serializer=prismGrpc__pb2.DeleteObjectRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.DeleteObjectResponse.FromString,
                )
        self.UploadFile = channel.stream_unary(
                '/PrismProtoService/UploadFile',
                request_serializer=prismGrpc__pb2.UploadRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.UploadReply.FromString,
                )
        self.Initialise = channel.unary_unary(
                '/PrismProtoService/Initialise',
                request_serializer=prismGrpc__pb2.InitialiseRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.InitialiseResponse.FromString,
                )
        self.ParseModelFile = channel.unary_unary(
                '/PrismProtoService/ParseModelFile',
                request_serializer=prismGrpc__pb2.ParseModelFileRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.ParseModelFileResponse.FromString,
                )
        self.LoadPRISMModel = channel.unary_unary(
                '/PrismProtoService/LoadPRISMModel',
                request_serializer=prismGrpc__pb2.LoadPRISMModelRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.LoadPRISMModelResponse.FromString,
                )
        self.ParsePropertiesFile = channel.unary_unary(
                '/PrismProtoService/ParsePropertiesFile',
                request_serializer=prismGrpc__pb2.ParsePropertiesFileRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.ParsePropertiesFileResponse.FromString,
                )
        self.GetPropertyObject = channel.unary_unary(
                '/PrismProtoService/GetPropertyObject',
                request_serializer=prismGrpc__pb2.GetPropertyObjectRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.GetPropertyObjectResponse.FromString,
                )
        self.ModelCheck = channel.unary_unary(
                '/PrismProtoService/ModelCheck',
                request_serializer=prismGrpc__pb2.ModelCheckRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.ModelCheckResponse.FromString,
                )
        self.GetUndefinedConstantsUsedInProperty = channel.unary_unary(
                '/PrismProtoService/GetUndefinedConstantsUsedInProperty',
                request_serializer=prismGrpc__pb2.GetUndefinedConstantsUsedInPropertyRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.GetUndefinedConstantsUsedInPropertyResponse.FromString,
                )
        self.AddValue = channel.unary_unary(
                '/PrismProtoService/AddValue',
                request_serializer=prismGrpc__pb2.AddValueRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.AddValueResponse.FromString,
                )
        self.SetSomeUndefinedConstants = channel.unary_unary(
                '/PrismProtoService/SetSomeUndefinedConstants',
                request_serializer=prismGrpc__pb2.SetSomeUndefinedConstantsRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.SetSomeUndefinedConstantsResponse.FromString,
                )
        self.DefineUsingConstSwitch = channel.unary_unary(
                '/PrismProtoService/DefineUsingConstSwitch',
                request_serializer=prismGrpc__pb2.DefineUsingConstSwitchRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.DefineUsingConstSwitchResponse.FromString,
                )
        self.GetNumberPropertyIterations = channel.unary_unary(
                '/PrismProtoService/GetNumberPropertyIterations',
                request_serializer=prismGrpc__pb2.GetNumberPropertyIterationsRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.GetNumberPropertyIterationsResponse.FromString,
                )
        self.GetPFConstantValues = channel.unary_unary(
                '/PrismProtoService/GetPFConstantValues',
                request_serializer=prismGrpc__pb2.GetPFConstantValuesRequest.SerializeToString,
                response_deserializer=prismGrpc__pb2.GetPFConstantValuesResponse.FromString,
                )


class PrismProtoServiceServicer(object):
    """Service Definitions
    """

    def InitPrismLog(self, request, context):
        """/////////////////////////////////////// Initializer /////////////////////////////////////////
        Prism Log
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitModulesFile(self, request, context):
        """ModulesFile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitPrism(self, request, context):
        """Prism
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitPropertiesFile(self, request, context):
        """PropertiesFile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitPropertyObject(self, request, context):
        """Property Object (called Property Object because "property" is a reserved word in Python)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitResult(self, request, context):
        """Result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitUndefinedConstants(self, request, context):
        """init undefined constants
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitValues(self, request, context):
        """Values
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteObject(self, request, context):
        """/////////////////////////////////////// Generic Functions /////////////////////////////////////////
        delete a PRISM object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """Generic method to upload files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Initialise(self, request, context):
        """/////////////////////////////////////// Object specific functions /////////////////////////////////////////
        Initialise the PRISM engine
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseModelFile(self, request, context):
        """Parse model file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadPRISMModel(self, request, context):
        """Load a PRISM model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParsePropertiesFile(self, request, context):
        """Parse a properties file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPropertyObject(self, request, context):
        """Get propety object from properties file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModelCheck(self, request, context):
        """Model check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUndefinedConstantsUsedInProperty(self, request, context):
        """Get undefined constants used in property
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddValue(self, request, context):
        """add values
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSomeUndefinedConstants(self, request, context):
        """set some undefined constants
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DefineUsingConstSwitch(self, request, context):
        """define using const switch for undefined constants
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNumberPropertyIterations(self, request, context):
        """get number of property iterations for undefined constants
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPFConstantValues(self, request, context):
        """get properties file constant values
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrismProtoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitPrismLog': grpc.unary_unary_rpc_method_handler(
                    servicer.InitPrismLog,
                    request_deserializer=prismGrpc__pb2.InitPrismLogRequest.FromString,
                    response_serializer=prismGrpc__pb2.InitResponse.SerializeToString,
            ),
            'InitModulesFile': grpc.unary_unary_rpc_method_handler(
                    servicer.InitModulesFile,
                    request_deserializer=prismGrpc__pb2.InitModulesFileRequest.FromString,
                    response_serializer=prismGrpc__pb2.InitResponse.SerializeToString,
            ),
            'InitPrism': grpc.unary_unary_rpc_method_handler(
                    servicer.InitPrism,
                    request_deserializer=prismGrpc__pb2.InitPrismRequest.FromString,
                    response_serializer=prismGrpc__pb2.InitResponse.SerializeToString,
            ),
            'InitPropertiesFile': grpc.unary_unary_rpc_method_handler(
                    servicer.InitPropertiesFile,
                    request_deserializer=prismGrpc__pb2.InitPropertiesFileRequest.FromString,
                    response_serializer=prismGrpc__pb2.InitResponse.SerializeToString,
            ),
            'InitPropertyObject': grpc.unary_unary_rpc_method_handler(
                    servicer.InitPropertyObject,
                    request_deserializer=prismGrpc__pb2.InitPropertyObjectRequest.FromString,
                    response_serializer=prismGrpc__pb2.InitResponse.SerializeToString,
            ),
            'InitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.InitResult,
                    request_deserializer=prismGrpc__pb2.InitResultRequest.FromString,
                    response_serializer=prismGrpc__pb2.InitResponse.SerializeToString,
            ),
            'InitUndefinedConstants': grpc.unary_unary_rpc_method_handler(
                    servicer.InitUndefinedConstants,
                    request_deserializer=prismGrpc__pb2.InitUndefinedConstantsRequest.FromString,
                    response_serializer=prismGrpc__pb2.InitResponse.SerializeToString,
            ),
            'InitValues': grpc.unary_unary_rpc_method_handler(
                    servicer.InitValues,
                    request_deserializer=prismGrpc__pb2.InitValuesRequest.FromString,
                    response_serializer=prismGrpc__pb2.InitResponse.SerializeToString,
            ),
            'DeleteObject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteObject,
                    request_deserializer=prismGrpc__pb2.DeleteObjectRequest.FromString,
                    response_serializer=prismGrpc__pb2.DeleteObjectResponse.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=prismGrpc__pb2.UploadRequest.FromString,
                    response_serializer=prismGrpc__pb2.UploadReply.SerializeToString,
            ),
            'Initialise': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialise,
                    request_deserializer=prismGrpc__pb2.InitialiseRequest.FromString,
                    response_serializer=prismGrpc__pb2.InitialiseResponse.SerializeToString,
            ),
            'ParseModelFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseModelFile,
                    request_deserializer=prismGrpc__pb2.ParseModelFileRequest.FromString,
                    response_serializer=prismGrpc__pb2.ParseModelFileResponse.SerializeToString,
            ),
            'LoadPRISMModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadPRISMModel,
                    request_deserializer=prismGrpc__pb2.LoadPRISMModelRequest.FromString,
                    response_serializer=prismGrpc__pb2.LoadPRISMModelResponse.SerializeToString,
            ),
            'ParsePropertiesFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ParsePropertiesFile,
                    request_deserializer=prismGrpc__pb2.ParsePropertiesFileRequest.FromString,
                    response_serializer=prismGrpc__pb2.ParsePropertiesFileResponse.SerializeToString,
            ),
            'GetPropertyObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPropertyObject,
                    request_deserializer=prismGrpc__pb2.GetPropertyObjectRequest.FromString,
                    response_serializer=prismGrpc__pb2.GetPropertyObjectResponse.SerializeToString,
            ),
            'ModelCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.ModelCheck,
                    request_deserializer=prismGrpc__pb2.ModelCheckRequest.FromString,
                    response_serializer=prismGrpc__pb2.ModelCheckResponse.SerializeToString,
            ),
            'GetUndefinedConstantsUsedInProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUndefinedConstantsUsedInProperty,
                    request_deserializer=prismGrpc__pb2.GetUndefinedConstantsUsedInPropertyRequest.FromString,
                    response_serializer=prismGrpc__pb2.GetUndefinedConstantsUsedInPropertyResponse.SerializeToString,
            ),
            'AddValue': grpc.unary_unary_rpc_method_handler(
                    servicer.AddValue,
                    request_deserializer=prismGrpc__pb2.AddValueRequest.FromString,
                    response_serializer=prismGrpc__pb2.AddValueResponse.SerializeToString,
            ),
            'SetSomeUndefinedConstants': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSomeUndefinedConstants,
                    request_deserializer=prismGrpc__pb2.SetSomeUndefinedConstantsRequest.FromString,
                    response_serializer=prismGrpc__pb2.SetSomeUndefinedConstantsResponse.SerializeToString,
            ),
            'DefineUsingConstSwitch': grpc.unary_unary_rpc_method_handler(
                    servicer.DefineUsingConstSwitch,
                    request_deserializer=prismGrpc__pb2.DefineUsingConstSwitchRequest.FromString,
                    response_serializer=prismGrpc__pb2.DefineUsingConstSwitchResponse.SerializeToString,
            ),
            'GetNumberPropertyIterations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNumberPropertyIterations,
                    request_deserializer=prismGrpc__pb2.GetNumberPropertyIterationsRequest.FromString,
                    response_serializer=prismGrpc__pb2.GetNumberPropertyIterationsResponse.SerializeToString,
            ),
            'GetPFConstantValues': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPFConstantValues,
                    request_deserializer=prismGrpc__pb2.GetPFConstantValuesRequest.FromString,
                    response_serializer=prismGrpc__pb2.GetPFConstantValuesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PrismProtoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PrismProtoService(object):
    """Service Definitions
    """

    @staticmethod
    def InitPrismLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/InitPrismLog',
            prismGrpc__pb2.InitPrismLogRequest.SerializeToString,
            prismGrpc__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitModulesFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/InitModulesFile',
            prismGrpc__pb2.InitModulesFileRequest.SerializeToString,
            prismGrpc__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitPrism(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/InitPrism',
            prismGrpc__pb2.InitPrismRequest.SerializeToString,
            prismGrpc__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitPropertiesFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/InitPropertiesFile',
            prismGrpc__pb2.InitPropertiesFileRequest.SerializeToString,
            prismGrpc__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitPropertyObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/InitPropertyObject',
            prismGrpc__pb2.InitPropertyObjectRequest.SerializeToString,
            prismGrpc__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/InitResult',
            prismGrpc__pb2.InitResultRequest.SerializeToString,
            prismGrpc__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitUndefinedConstants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/InitUndefinedConstants',
            prismGrpc__pb2.InitUndefinedConstantsRequest.SerializeToString,
            prismGrpc__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/InitValues',
            prismGrpc__pb2.InitValuesRequest.SerializeToString,
            prismGrpc__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/DeleteObject',
            prismGrpc__pb2.DeleteObjectRequest.SerializeToString,
            prismGrpc__pb2.DeleteObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/PrismProtoService/UploadFile',
            prismGrpc__pb2.UploadRequest.SerializeToString,
            prismGrpc__pb2.UploadReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Initialise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/Initialise',
            prismGrpc__pb2.InitialiseRequest.SerializeToString,
            prismGrpc__pb2.InitialiseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ParseModelFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/ParseModelFile',
            prismGrpc__pb2.ParseModelFileRequest.SerializeToString,
            prismGrpc__pb2.ParseModelFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadPRISMModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/LoadPRISMModel',
            prismGrpc__pb2.LoadPRISMModelRequest.SerializeToString,
            prismGrpc__pb2.LoadPRISMModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ParsePropertiesFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/ParsePropertiesFile',
            prismGrpc__pb2.ParsePropertiesFileRequest.SerializeToString,
            prismGrpc__pb2.ParsePropertiesFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPropertyObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/GetPropertyObject',
            prismGrpc__pb2.GetPropertyObjectRequest.SerializeToString,
            prismGrpc__pb2.GetPropertyObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModelCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/ModelCheck',
            prismGrpc__pb2.ModelCheckRequest.SerializeToString,
            prismGrpc__pb2.ModelCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUndefinedConstantsUsedInProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/GetUndefinedConstantsUsedInProperty',
            prismGrpc__pb2.GetUndefinedConstantsUsedInPropertyRequest.SerializeToString,
            prismGrpc__pb2.GetUndefinedConstantsUsedInPropertyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/AddValue',
            prismGrpc__pb2.AddValueRequest.SerializeToString,
            prismGrpc__pb2.AddValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSomeUndefinedConstants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/SetSomeUndefinedConstants',
            prismGrpc__pb2.SetSomeUndefinedConstantsRequest.SerializeToString,
            prismGrpc__pb2.SetSomeUndefinedConstantsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DefineUsingConstSwitch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/DefineUsingConstSwitch',
            prismGrpc__pb2.DefineUsingConstSwitchRequest.SerializeToString,
            prismGrpc__pb2.DefineUsingConstSwitchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNumberPropertyIterations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/GetNumberPropertyIterations',
            prismGrpc__pb2.GetNumberPropertyIterationsRequest.SerializeToString,
            prismGrpc__pb2.GetNumberPropertyIterationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPFConstantValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrismProtoService/GetPFConstantValues',
            prismGrpc__pb2.GetPFConstantValuesRequest.SerializeToString,
            prismGrpc__pb2.GetPFConstantValuesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
