#!/bin/bash         

STORM_POMDP="/Users/shengsheng/Downloads/github/storm-test/storm/build/bin/storm-pomdp"
#MODEL_DIR="/Users/shengsheng/Dropbox/files/obstacles/N6
# MODEL_DIR="/Users/shengsheng/Dropbox/files/obstacles/N50"
# MODEL_DIR="/Users/shengsheng/Dropbox/files/refuel/N6E8"
# MODEL_DIR="/Users/shengsheng/Dropbox/files/rock/N8R2"

TO=99998000
TIMEOUTCOMMAND="timeout $TO"

# model="refule_N6E8_factored-3-3-0-5-2.nm"
# $STORM_POMDP --prism ${MODEL_DIR}/${model} --prop "Pmax=? [\"notbad\" U \"goal\"]" --buildstateval --build-all-labels --qualitative-analysis --memlesssearch iterative --winningregion -stats --exportwinningregion "${MODEL_DIR}/winningregion/${model%.*}-fixpoint.wr" &> "${MODEL_DIR}/log/${model%.*}-fixpoint.wr.log"


MODEL_FILE=$(ls $MODEL_DIR/*factor*.nm)
for path_model in $MODEL_FILE; do
  model=$(basename $path_model)
  # model="refule_N6E8_factored-3-3-0-5-2.nm"
  # echo $model
  $STORM_POMDP --prism ${MODEL_DIR}/${model} --exportbuild ${MODEL_DIR}/log/${model%.*}.dot --prop "Pmax=? [\"notbad\" U \"goal\"]" --buildstateval --build-all-labels --qualitative-analysis --memlesssearch iterative --winningregion -stats --exportwinningregion "${MODEL_DIR}/winningregion/${model%.*}-fixpoint.wr" &> "${MODEL_DIR}/log/${model%.*}-fixpoint.wr.log"
done
