#!/bin/bash         

STORM_BUILD_DIR="/opt/storm/build"
STORM_POMDP="${STORM_BUILD_DIR}/bin/storm-pomdp"
echo "Storm-binary: $STORM_POMDP"

echo "Models expected at folder /opt/gridstorm/gridstorm/models/files/"
MODEL_DIR=/files/rock/N8R2/

TO=99998000
echo "Time out is $TO seconds"
TIMEOUTCOMMAND="timeout $TO"

model=rocks_N8R2_centralized
$TIMEOUTCOMMAND $STORM_POMDP --prism $MODEL_DIR/$model.nm -const N=8 --prop "Pmax=? [\"notbad\" U \"goal\"]"  \
  --buildstateval --build-all-labels --qualitative-analysis --memlesssearch iterative --winningregion -stats \
  --exportwinningregion "winningregion/$model-fixpoint.wr" &> logfiles/iterative/$model-fixpoint.wr.log
