#!/bin/bash         

STORM_POMDP="/Users/shengsheng/Downloads/github/storm-test/storm/build/bin/storm-pomdp"

MODEL_DIR="/Users/shengsheng/Dropbox/files/rock/N8R2/"
#/files/rock/N8R2/

TO=99998000
echo "Time out is $TO seconds"
TIMEOUTCOMMAND="timeout $TO"

model=rocks_N8R2_centralized
$TIMEOUTCOMMAND $STORM_POMDP --prism $MODEL_DIR/$model.nm -const N=8 --prop "Pmax=? [\"notbad\" U \"goal\"]"  \
  --buildstateval --build-all-labels --qualitative-analysis --memlesssearch iterative --winningregion -stats \
  --exportwinningregion "winningregion/$model-fixpoint.wr" &> logfiles/iterative/$model-fixpoint.wr.log
